### ISSUE TITLE
Problem while reindexing cms page

### ISSUE THREAD

**Issue by nitikeshd** [DivanteLtd/magento2-vsbridge-indexer#281]
Command:
 php bin/magento vsbridge:reindex --store=en_us

Output:
```
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:04
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Product Indexer index has been rebuilt successfully in 00:01:51
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:00
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Divante\VsbridgeIndexerCms\Model\ContentProcessor::parse() must be of the type string, null given, called in /var/www/html/webapp/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/CmsContentFilter.php on line 77 and defined in /var/www/html/webapp/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/ContentProcessor.php:23

Stack trace:
#0 /var/www/html/webapp/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/CmsContentFilter.php(77): Divante\VsbridgeIndexerCms\Model\ContentProcessor->parse(Object(Magento\Widget\Model\Template\FilterEmulate\Interceptor), NULL)

#1 /var/www/html/webapp/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/Page/ContentData.php(39): Divante\VsbridgeIndexerCms\Model\Indexer\DataProvider\CmsContentFilter->filter(Array, 2, 'page')

#2 /var/www/html/webapp/vendor/divante/magen in /var/www/html/webapp/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/ContentProcessor.php on line 23
```
Can anyone please help me out on this?

**Comment by janmyszkier** [comment]
@nitikeshd are you using the master branch?
looks like 
https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/master/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/CmsContentFilter.php#L77
already has a fix for this by casting the variable into string.

**Comment by nitikeshd** [comment]
I see. Yes i am using master branch.

**Comment by afirlejczyk** [comment]
Changes were not updated in the packagist, please update module/use 1.17.0 version
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/276
