### ISSUE TITLE
no such index [vue_storefront_catalog_taxrule]

### ISSUE THREAD

**Issue by WinstonN** [DivanteLtd/magento2-vsbridge-indexer#314]
Hello

I installed the 2X version of the vs bridge in Magento (with sample data), and indexing data into ES v7

When using the GraphQL to run this query
```
{
  products(
    filter: {
      sku: {
        like: "24-MB01"
      }
    }
  )
  {
    hits
  }
}
```
I get this error
```
app_1    | (node:73) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
app_1    |     at SearchQuery.hasAppliedSort (/var/www/node_modules/storefront-query-builder/src/types/SearchQuery.ts:48:30)
app_1    |     at RequestBody.applySort (/var/www/node_modules/storefront-query-builder/src/elasticsearch/body.ts:336:26)
app_1    |     at RequestBody.buildQueryBodyFromSearchQuery (/var/www/node_modules/storefront-query-builder/src/elasticsearch/body.ts:189:10)
app_1    |     at /var/www/node_modules/storefront-query-builder/src/elasticsearch/index.ts:11:17
app_1    |     at step (/var/www/node_modules/storefront-query-builder/lib/elasticsearch/index.js:33:23)
app_1    |     at Object.next (/var/www/node_modules/storefront-query-builder/lib/elasticsearch/index.js:14:53)
app_1    |     at /var/www/node_modules/storefront-query-builder/lib/elasticsearch/index.js:8:71
app_1    |     at new Promise (<anonymous>)
app_1    |     at __awaiter (/var/www/node_modules/storefront-query-builder/lib/elasticsearch/index.js:4:12)
app_1    |     at buildQueryBodyFromSearchQuery (/var/www/node_modules/storefront-query-builder/lib/elasticsearch/index.js:50:12)
app_1    | (node:73) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
app_1    | [Storefront-API] 73   - 07/22/2020, 9:33:12 AM  Object:
app_1    | {
app_1    |   "name": "ResponseError",
app_1    |   "meta": {
app_1    |     "body": {
app_1    |       "error": {
app_1    |         "root_cause": [
app_1    |           {
app_1    |             "type": "index_not_found_exception",
app_1    |             "reason": "no such index [vue_storefront_catalog_taxrule]",
app_1    |             "resource.type": "index_or_alias",
app_1    |             "resource.id": "vue_storefront_catalog_taxrule",
app_1    |             "index_uuid": "_na_",
app_1    |             "index": "vue_storefront_catalog_taxrule"
app_1    |           }
app_1    |         ],
app_1    |         "type": "index_not_found_exception",
app_1    |         "reason": "no such index [vue_storefront_catalog_taxrule]",
app_1    |         "resource.type": "index_or_alias",
app_1    |         "resource.id": "vue_storefront_catalog_taxrule",
app_1    |         "index_uuid": "_na_",
app_1    |         "index": "vue_storefront_catalog_taxrule"
app_1    |       },
app_1    |       "status": 404
app_1    |     },
app_1    |     "statusCode": 404,
app_1    |     "headers": {
app_1    |       "content-type": "application/json; charset=UTF-8",
app_1    |       "content-length": "509"
app_1    |     },
app_1    |     "warnings": null,
app_1    |     "meta": {
app_1    |       "context": null,
app_1    |       "request": {
app_1    |         "params": {
app_1    |           "method": "POST",
app_1    |           "path": "/vue_storefront_catalog_taxrule/_search",
app_1    |           "body": "{}",
app_1    |           "querystring": "",
app_1    |           "headers": {
app_1    |             "user-agent": "elasticsearch-js/7.7.1 (linux 4.19.76-linuxkit-x64; Node.js v10.21.0)",
app_1    |             "content-type": "application/json",
app_1    |             "content-length": "2"
app_1    |           },
app_1    |           "timeout": 5000
app_1    |         },
app_1    |         "options": {
app_1    |           "warnings": null
app_1    |         },
app_1    |         "id": 1
app_1    |       },
app_1    |       "name": "elasticsearch-js",
app_1    |       "connection": {
app_1    |         "url": "http://sfa_elasticsearch:9200/",
app_1    |         "id": "http://sfa_elasticsearch:9200/",
app_1    |         "headers": {},
app_1    |         "deadCount": 0,
app_1    |         "resurrectTimeout": 0,
app_1    |         "_openRequests": 0,
app_1    |         "status": "alive",
app_1    |         "roles": {
app_1    |           "master": true,
app_1    |           "data": true,
app_1    |           "ingest": true,
app_1    |           "ml": false
app_1    |         }
app_1    |       },
app_1    |       "attempts": 0,
app_1    |       "aborted": false
app_1    |     }
app_1    |   }
app_1    | }
app_1    |  +1565728ms
app_1    | POST /graphql - - ms - -
```

When I run `bin/magento in:rei` I get
```
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:02
Product EAV index has been rebuilt successfully in 00:00:01
Product Price index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:01
Catalog Search index has been rebuilt successfully in 00:00:03
Vsbridge Agreement Indexer indexer process unknown error:
{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [index.mapping.total_fields.limit] for create index"}],"type":"parse_exception","reason":"unknown key [index.mapping.total_fields.limit] for create index"},"status":400}
Vsbridge Product Indexer index has been rebuilt successfully in 00:00:09
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:01
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:01
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:05
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:02
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
```
In ES I have the following indexes, after the index
![image](https://user-images.githubusercontent.com/1143789/88161824-98c40300-cc64-11ea-87d3-2e3eb96cae36.png)

Can you see where the issue is?

**Comment by afirlejczyk** [comment]
Hello.
What exact version of ES 7 instance do you have?

**Comment by WinstonN** [comment]
@afirlejczyk 
```
version.number 7.3.2
```

**Comment by afirlejczyk** [comment]
OK, I tested branch 2.x and it's is working with ES 7.3.2 without a problem.

Are you sure you are on the correct branch because you can have this error when you are using changes from the master branch or from the 1.x version.

```
{
  "name" : "11746f32b224",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "QMf2sjJERl2O9ZjmL_utZg",
  "version" : {
    "number" : "7.3.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "1c1faf1",
    "build_date" : "2019-09-06T14:40:30.409026Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
app@a6b3a6f5ad70:~/html$ php bin/magento vsbridge:reindex --store 1
Reindexing all VS indexes for store Default Store View...
Vsbridge Agreement Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Product Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:09
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:01
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
Reindexing has completed!
```

**Comment by WinstonN** [comment]
@afirlejczyk Your instructions worked - Thank you

Adding some context, I followed the instructions below, when I originally installed the vs bridge

installation instructions: https://github.com/DivanteLtd/magento2-vsbridge-indexer/tree/2.x
config setup instructions: https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/2.x/docs/configuration.md 

When I used your instructions I received the error
```
❯❯❯ composer require divante/magento2-vsbridge-indexer:2.x
    1/3:	https://repo.packagist.org/p/provider-2020-01$620c5563a8a00a1ce6a291fe151a4aa64fc66e6dacd3330b2ec9f061f704f689.json
    2/3:	https://repo.packagist.org/p/provider-latest$c24a57bf0d8a41a98a28f02aeb53c95110f9fc2c17ca70a504f9f0bebe34affc.json
    3/3:	https://repo.packagist.org/p/provider-2020-04$050c267181b1a6655cb070cab16e154de4863d9ac9e6e49d604841e74dbe2ca6.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package divante/magento2-vsbridge-indexer 2.x is satisfiable by divante/magento2-vsbridge-indexer[2.0-alpha, 2.x-dev] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
I fixed it by running
```
❯❯❯ composer require divante/magento2-vsbridge-indexer:2.x@dev
```
Thank you very much for the help <3

**Comment by afirlejczyk** [comment]
OK, I might have a different configuration in my Magento composer.json, so that's why my solution worked for me.

Yes, 2.0-alpha or 2.x-dev is the equivalent. 
I'm glad the problem is solved.
