### ISSUE TITLE
preg_match() expects parameter 2 to be string, null given

### ISSUE THREAD

**Issue by ldc321** [DivanteLtd/magento2-vsbridge-indexer#331]
Fatal error: Uncaught TypeError: preg_match() expects parameter 2 to be string, null given in /www/wwwroot/migrate.olightstore.ca/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Product/LoadMediaGallery.php:157
Stack trace:
#0 /www/wwwroot/migrate.olightstore.ca/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Product/LoadMediaGallery.php(157): preg_match('%(?:youtube(?:-...', NULL, Array)
#1 /www/wwwroot/migrate.olightstore.ca/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Product/LoadMediaGallery.php(96): Divante\VsbridgeIndexerCatalog\Model\Product\LoadMediaGallery->prepareVideoData(Array)
#2 /www/wwwroot/migrate.olightstore.ca/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Indexer/DataProvider/Product/MediaGalleryData.php(56): Divante\VsbridgeIndexerCatalog\Model\Product\LoadMediaGallery->execute(Array, 1)
#3 /www/wwwroot/migrate.olightstore.ca/vendor/divante/magento2-vsbridge-in in /www/wwwroot/migrate.olightstore.ca/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Product/LoadMediaGallery.php on line 157

**Comment by ldc321** [comment]
**run: php bin/magento indexer:reindex vsbridge_cms_block_indexer**
PHP Fatal error:  Uncaught TypeError: Return value of Magento\PageBuilder\Model\Stage\Preview::isPreviewMode() must be of the type boolean, null returned in /www/wwwroot/m23.olightstore.ca/vendor/magento/module-page-builder/Model/Stage/Preview.php:132
