### ISSUE TITLE
Compatibility issues with Magento 2.4.4

### ISSUE THREAD

**Issue by tajveez-73** [DivanteLtd/magento2-vsbridge-indexer#405]
Hello, Magento 2.4.4 is out and uses PHP version 8.1. Here's one of the errors we are getting due to depreciation issues.

`main.CRITICAL: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in http/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/ResourceModel/AbstractEavAttributes.php on line 17`

**Comment by simonmaass** [comment]
i am also getting this error


```
There is an error in /vendor/symfony/console/Command/Command.php at line: 301
Return value of "Divante\VsbridgeIndexerCore\Console\Command\RebuildEsIndexCommand\Interceptor::execute()" must be of the type int, "null" returned.#0 /vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /vendor/magento/framework/Interception/Interceptor.php(138): Divante\VsbridgeIndexerCore\Console\Command\RebuildEsIndexCommand\Interceptor->___callParent('run', Array)
#2 /vendor/magento/framework/Interception/Interceptor.php(153): Divante\VsbridgeIndexerCore\Console\Command\RebuildEsIndexCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /generated/code/Divante/VsbridgeIndexerCore/Console/Command/RebuildEsIndexCommand/Interceptor.php(77): Divante\VsbridgeIndexerCore\Console\Command\RebuildEsIndexCommand\Interceptor->___callPlugins('run', Array, Array)
#4 /vendor/symfony/console/Application.php(1040): Divante\VsbridgeIndexerCore\Console\Command\RebuildEsIndexCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Divante\VsbridgeIndexerCore\Console\Command\RebuildEsIndexCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /bin/magento(23): Symfony\Component\Console\Application->run()
#9 {main}

```
